export const DEMO_USER = {
  userId: 'demo',
  fullName: 'مستخدم تجريبي',
  userName: 'demo',
  email: 'demo@crm.com',
};

export const DEMO_STATS = {
  totalProjects: 5,
  activeProjects: 3,
  completedProjects: 1,
  pendingApprovals: 4,
  overallProgress: 62,
  recentProjects: [
    { id: 1, title: 'مشروع إنشاء مجمع سكني', branch: { name: 'الفرع الرئيسي' } },
    { id: 2, title: 'مشروع تطوير البنية التحتية', branch: { name: 'فرع الشمال' } },
    { id: 3, title: 'مشروع توسعة المصنع', branch: { name: 'فرع الجنوب' } },
  ],
};

export const DEMO_PROJECTS = [
  {
    id: 1,
    title: 'مشروع إنشاء مجمع سكني',
    code: 'PRJ-001',
    statusId: 2,
    progress: 75,
    branch: { name: 'الفرع الرئيسي' },
    customer: { localName: 'شركة الإعمار' },
    startDate: '2025-01-01',
    endDate: '2026-06-30',
    totalValue: 5000000,
  },
  {
    id: 2,
    title: 'مشروع تطوير البنية التحتية',
    code: 'PRJ-002',
    statusId: 2,
    progress: 40,
    branch: { name: 'فرع الشمال' },
    customer: { localName: 'بلدية المدينة' },
    startDate: '2025-03-01',
    endDate: '2026-12-31',
    totalValue: 12000000,
  },
  {
    id: 3,
    title: 'مشروع توسعة المصنع',
    code: 'PRJ-003',
    statusId: 2,
    progress: 90,
    branch: { name: 'فرع الجنوب' },
    customer: { localName: 'مصنع الأمل' },
    startDate: '2024-06-01',
    endDate: '2025-12-31',
    totalValue: 3500000,
  },
  {
    id: 4,
    title: 'مشروع صيانة الطرق',
    code: 'PRJ-004',
    statusId: 5,
    progress: 100,
    branch: { name: 'الفرع الرئيسي' },
    customer: { localName: 'وزارة الأشغال' },
    startDate: '2024-01-01',
    endDate: '2025-01-01',
    totalValue: 800000,
  },
  {
    id: 5,
    title: 'مشروع إنشاء محطة معالجة',
    code: 'PRJ-005',
    statusId: 1,
    progress: 0,
    branch: { name: 'فرع الشرق' },
    customer: { localName: 'شركة المياه الوطنية' },
    startDate: '2026-01-01',
    endDate: '2027-06-30',
    totalValue: 9000000,
  },
];

export const DEMO_PROJECT_DETAIL = {
  id: 1,
  title: 'مشروع إنشاء مجمع سكني',
  code: 'PRJ-001',
  statusId: 2,
  progress: 75,
  branch: { name: 'الفرع الرئيسي' },
  customer: { localName: 'شركة الإعمار' },
  startDate: '2025-01-01T00:00:00',
  endDate: '2026-06-30T00:00:00',
  totalValue: 5000000,
  notes: 'مشروع إنشاء مجمع سكني متكامل يضم 120 وحدة سكنية',
  scopes: [
    {
      id: 1,
      title: 'أعمال الهيكل الإنشائي',
      statusId: 2,
      progress: 85,
      stages: [
        { id: 1, title: 'الأساسات', statusId: 3, progress: 100 },
        { id: 2, title: 'الأعمدة والأسقف', statusId: 2, progress: 80 },
        { id: 3, title: 'الجدران', statusId: 1, progress: 20 },
      ],
    },
    {
      id: 2,
      title: 'الأعمال الميكانيكية والكهربائية',
      statusId: 1,
      progress: 30,
      stages: [
        { id: 4, title: 'التمديدات الكهربائية', statusId: 1, progress: 30 },
        { id: 5, title: 'تمديدات السباكة', statusId: 1, progress: 25 },
      ],
    },
  ],
};

export const DEMO_APPROVALS = [
  {
    id: 1,
    requestType: 'طلب وحدات',
    projectTitle: 'مشروع إنشاء مجمع سكني',
    requestedBy: 'أحمد محمد',
    requestDate: '2026-08-05T10:00:00',
    statusId: 1,
    quantity: 50,
    unitName: 'طن اسمنت',
  },
  {
    id: 2,
    requestType: 'طلب وحدات',
    projectTitle: 'مشروع تطوير البنية التحتية',
    requestedBy: 'محمد علي',
    requestDate: '2026-08-07T09:00:00',
    statusId: 1,
    quantity: 200,
    unitName: 'متر حديد',
  },
  {
    id: 3,
    requestType: 'طلب وحدات',
    projectTitle: 'مشروع توسعة المصنع',
    requestedBy: 'سارة أحمد',
    requestDate: '2026-08-08T11:00:00',
    statusId: 1,
    quantity: 30,
    unitName: 'م² بلاط',
  },
  {
    id: 4,
    requestType: 'طلب وحدات',
    projectTitle: 'مشروع إنشاء محطة معالجة',
    requestedBy: 'خالد عمر',
    requestDate: '2026-08-09T08:00:00',
    statusId: 1,
    quantity: 15,
    unitName: 'ضخ مياه',
  },
];
